#!/bin/bash
# This script should be launched from the repertory where the .csv files exist

# Loads, into a mysql table, lines of csv files generated by filesCompare.py, with the write_result_csv function of bgpCompare.py

# Create a mysql table in a database named mydb, user is root and pasword is toto
/usr/local/mysql/bin/mysql -u root -ptoto mydb -e "drop table precisionRecall;"
/usr/local/mysql/bin/mysql -u root -ptoto mydb -e "create table precisionRecall(
date_ varchar(20),
ip varchar(33),
bgp_dbp varchar(2000),
bgp_lift varchar(2000),
nb_occurrences_dbp int(4),
nb_occurrences_lift int(4),
rank_dbp int(5),
rank_lift int(5),
preci DECIMAL(6,5),
recall DECIMAL(6,5)
);"

# Precision table should be empty to avoid having duplicates.
# /usr/local/mysql/bin/mysql -u root -porion mydb -e "delete from precisionRecall";
# echo "Table traces has been emptied"

# All precisionRecall.csv files are loaded into the precision table.
for file in *precisionRecall.csv
do
	echo "Loading file $file ..."
	/usr/local/mysql/bin/mysql -u root -porion mydb -e "
      LOAD DATA LOCAL INFILE '$file'
      INTO TABLE precisionRecall 
      FIELDS TERMINATED BY ';' 
      LINES TERMINATED BY '\n'
		IGNORE 1 LINES;
		show WARNINGS"
done